# -*- coding: utf-8 -*-
"""Untitled3.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vFllsx9xIKJZ0GGcbtUTcAB9fErpxEpJ
"""

#202102892 임준엽
import pandas as pd
#문제 1
df= pd.read_csv('http://raw.githubusercontent.com/gundaminpde/2022/main/titanic.csv')
df

#문제 2
print('앞 행 10개는 아래와 같다.')
print(df.head(10))

#문제 3
print('뒤 행 10개는 아래와 같다.')
print(df.tail(10))

#문제 4
print("모양: ", df.shape)

#문제 5
print(df.columns)

#문제 6
print(df.loc[5:15,['Name', 'Age', 'Survived']])

#문제 7 
df.loc[5:15:2,['Name', 'Age', 'Survived']]

#문제 8
print(df.iloc[[0,5,50],[1,2,5]])

#문제 9
print(df.groupby("Sex")[["Age","Sex"]].mean())
#데이터타입 어케아노?

#문제 10
print(df.groupby('Sex')['Age'].agg(['max']))
#데이터는 뭐고

#문제11 
df[ df['Age']> df['Age'].mean()].head(n=7)

#문제 12
import os

print(os.getcwd())
os.chdir('/home')
names = df['Name'] 
names.to_pickle('/home/their_names.pickle')
return_names = pd.read_pickle('/home/their_names.pickle')
print(return_names)

#문제 13

import seaborn as sns

sns.set_theme()
sns.set(rc={"figure.dpi":300})
sns.set(rc={"figure.figsize": (6,3)})

sns.scatterplot(data=df, x="Age", y="Survived",hue= "Sex")

#문제 14
sns.displot(x="Age",data=df[df["Survived"]==1],kde= "True")

#문제 15 
sns.boxplot(x=df['Sex'],y=df['Age'], data=df["Survived"]==0)